---
editor:
    render-on-save: true
---

### Population mean fitness uncertainty $\pi(\underline{\bar{s}}_T \mid \underline{\underline{F}}, \underline{\underline{R}})$ {#sec-bayes_meanfit}

Next, we turn our attention to the problem of determining the population mean
fitnesses $\underline{\bar{s}}_T$. First, we notice that our fitness model in
@eq-fitness does not include the value of the raw reads. They enter the
calculation indirectly through the inference of the frequency values we
developed in @sec-bayes_freq. This means that we can remove the conditioning of
the value of $\underline{\bar{s}}_T$ on the number of reads, obtaining a simpler
probability function
$$
\pi(
    \underline{\bar{s}}_T \mid 
    \underline{\underline{F}}, \underline{\underline{R}}
) = 
\pi(
    \underline{\bar{s}}_T \mid 
    \underline{\underline{F}}
).
$${#eq-meanfit_noreads}
Moreover, our fitness model does not directly explain how the population mean
fitness evolves over time. In other words, our model cannot explicitly compute
the population mean fitness at time $t+1$ from the information we have about
time $t$. Given this model limitation, we are led to assume that we must infer
each $\bar{s}_t$ independently. Expressing this for our inference
results in
$$
\pi(
    \underline{\bar{s}}_T \mid 
    \underline{\underline{F}}
) =
\prod_{t=1}^{T-1} \pi(\bar{s}_t \mid \underline{f}_t, \underline{f}_{t+1}),
$${#eq-meanfit_indep}
where we split our matrix $\underline{\underline{F}}$ for each time point and
only kept the conditioning on the relevant frequencies needed to compute the
mean fitness at time $t$.

Although our fitness model in @eq-fitness also includes the relative fitness
$s^{(m)}$, to infer the population mean fitness we only utilize data from the
neutral lineages that, by definition, have a relative fitness $s^{(n)} = 0$.
Therefore, the conditioning on @eq-meanfit_indep can be further simplified by
only keeping the frequencies of the neutral lineages, i.e.,
$$
\pi(\bar{s}_t \mid \underline{f}_t, \underline{f}_{t+1}) =
\pi(\bar{s}_t \mid \underline{f}_t^N, \underline{f}_{t+1}^N).
$${#eq-meanfit_indep_neutral}

Recall that in @sec-fitness_model we emphasized that the frequencies $f_t^{(n)}$
do not represent the true frequency of a particular lineage in the population
but rather a "normalized number of cells." Therefore, it is safe to assume each
of the $N$ neutral lineages' frequencies is changing independently. The
correlation of how increasing the frequency of one lineage will decrease the
frequency of others is already captured in the model presented in
@sec-bayes_freq. Thus, we write
$$
\pi(\bar{s}_t \mid \underline{f}_t^N, \underline{f}_{t+1}^N) =
\prod_{n=1}^N \pi(\bar{s}_t \mid f_t^{(n)}, f_{t+1}^{(n)}).
$${#eq-meanfit_indep_lineages}

Now, we can focus on one of the terms on the right-hand side of
@eq-meanfit_indep_lineages. Writing Bayes theorem results in
$$
\pi(\bar{s}_t \mid f_t^{(n)}, f_{t+1}^{(n)}) \propto
\pi(f_t^{(n)}, f_{t+1}^{(n)} \mid \bar{s}_t) \pi(\bar{s}_t).
$${#eq-meanfit_bayes}
Notice the likelihood defines the joint distribution of neutral barcode
frequencies conditioned on the population mean fitness. However, rewriting our
fitness model in @eq-fitness for a neutral lineage to leave frequencies on one
side and fitness on the other results in
$$
\frac{f_{t+1}^{(n)}}{f_t^{(n)}} = \mathrm{e}^{- \bar{s}_t}\tau.
$${#eq-fitness_ratio_neutral}
@eq-fitness_ratio_neutral implies that our fitness model only relates **the
ratio** of frequencies and not the individual values. To get around this 
complication, we define
$$
\gamma_t^{(b)} \equiv \frac{f_{t+1}^{(b)}}{f_t^{(b)}},
$${#eq-gamma_def}
as the ratio of frequencies between two adjacent time points for any barcode
$b$. This allows us to rewrite the joint distribution
$\pi(f_t^{(n)}, f_{t+1}^{(n)} \mid \bar{s}_t)$ as
$$
\pi(f_t^{(n)}, f_{t+1}^{(n)} \mid \bar{s}_t) =
\pi(f_t^{(n)}, \gamma_{t}^{(n)} \mid \bar{s}_t).
$${#eq-joint_freq_gamma}
Let us rephrase this subtle but necessary change of variables since it is a key
part of the inference problem: our series of independence assumptions lead us to
@eq-meanfit_bayes that relates the value of the population mean fitness
$\bar{s}_t$ to the frequency of a neutral barcode at times $t$ and $t+1$. 
However, as shown in @eq-fitness_ratio_neutral, our model functionally relates
the ratio of frequencies---that we defined as $\gamma_t^{(n)}$---and not the
independent frequencies to the mean fitness. Therefore, instead of writing for
the likelihood the joint distribution of the frequency values at times $t$ and
$t+1$ conditioned on the mean fitness, we write the joint distribution of the
barcode frequency at time $t$ and the ratio of the frequencies. These **must
be** equivalent joint distributions since there is a one-to-one mapping between
$\gamma_t^{(n)}$ and $f_{t+1}^{(n)}$ for a given value of $f_t^{(n)}$. Another
way to phrase this is to say that knowing the frequency at time $t$ and at time
$t+1$ provides the same amount of information as knowing the frequency at time
$t$ and the ratio of the frequencies. This is because if we want to obtain
$f_{t+1}^{(n)}$ given this information, we simply compute
$$
f_{t+1}^{(n)} = \gamma_t^{(n)} f_t^{(n)}.
$${#eq-meanfit_ft+1_gamma}

The real advantage of rewriting the joint distribution as in
@eq-joint_freq_gamma comes from splitting this joint distribution as a product
of conditional distributions of the form
$$
\pi(f_t^{(n)}, \gamma_{t}^{(n)} \mid \bar{s}_t) =
\pi(f_t^{(n)} \mid \gamma_{t}^{(n)}, \bar{s}_t)
\pi(\gamma_{t}^{(n)} \mid \bar{s}_t).
$${#eq-joint_to_prod_gamma}
Written in this form, we can finally propose a probabilistic model for how the
mean fitness relates to the frequency ratios we determine in our experiments.
The second term on the right-hand side of @eq-joint_to_prod_gamma relates how
the determined frequency ratio $\gamma_t^{(b)}$ relates to the mean fitness
$\bar{s}_t$. From @eq-fitness_ratio_neutral and @eq-gamma_def, we can write
$$
\ln \gamma_t^{(n)} = - \bar{s}_t + \varepsilon_t^{(n)},
$${#eq-log_ratio_neutral}
where, for simplicity, we set $\tau = 1$. Note that we added an extra term,
$\varepsilon_t^{(n)}$, characterizing the deviations of the measurements from
the theoretical model. It is common to assume that these errors are normally
distributed with mean zero and some standard deviation $\sigma_t$, implying that
$$
\ln \gamma_t^{(n)} \mid \bar{s}_t, \sigma_t  \sim 
\mathcal{N}\left(-\bar{s}_t, \sigma_t \right),
$${#eq-log_gamma_normal}
where we include the nuisance parameter $\sigma_t$ to be determined. If we 
assume the log frequency ratio is normally distributed, this implies the 
frequency ratio itself is distributed log-normal. This means that
$$
\gamma_t^{(n)} \mid \bar{s}_t, \sigma_t  \sim 
\log \mathcal{N}\left(-\bar{s}_t, \sigma_t \right).
$${#eq-meanfit_likelihood}
Having added the nuisance parameter $\sigma_t$ implies that we must update
@eq-meanfit_bayes to
$$
\pi(\bar{s}_t, \sigma_t \mid f_t^{(n)}, f_{t+1}^{(n)}) \propto
\pi(f_t^{(n)}, \gamma_t^{(n)} \mid \bar{s}_t, \sigma_t) 
\pi(\bar{s}_t) \pi(\sigma_t),
$${#eq-meanfit_bayes_full}
where we assume the prior for each parameter is independent, i.e.,
$$
\pi(\bar{s}_t, \sigma_t) = \pi(\bar{s}_t) \pi(\sigma_t).
$${#eq-meanfit_indep_prior}
For numerical stability, we will select weakly-informative priors for both of
these parameters. In the case of the nuisance parameter $\sigma_t$, the prior
must be restricted to positive values only, since standard deviations cannot be
negative.

For the first term on the right-hand side of @eq-joint_to_prod_gamma,
$\pi(f_t^{(n)} \mid \gamma_{t}^{(n)}, \bar{s}_t)$, we remove the conditioning
on the population mean fitness since it does not add any information on top of
what the frequency ratio $\gamma_t^{(n)}$ already gives. Therefore, we have
$$
\pi(f_t^{(n)} \mid \gamma_{t}^{(n)}, \bar{s}_t) =
\pi(f_t^{(n)} \mid \gamma_{t}^{(n)}).
$${#eq-freq_cond_gamma}
The right-hand side of @eq-freq_cond_gamma asks us to compute the probability
of observing a frequency value $f_t^{(n)}$ given that we get to observe the
ratio $\gamma_{t}^{(n)}$. If the ratio happened to be $\gamma_{t}^{(n)} = 2$,
we could have $f_{t+1}^{(n)} = 1$ and $f_{t+1}^{(n)} = 0.5$, for example.
Although, it would be equally likely that $f_{t+1}^{(n)} = 0.6$ and
$f_{t+1}^{(n)} = 0.3$ or $f_{t+1}^{(n)} = 0.1$ and $f_{t+1}^{(n)} = 0.05$ for
that matter. If we only get to observe the frequency ratio $\gamma_t^{(n)}$, we
know that the numerator $f_{t+1}^{(n)}$ can only take values between zero and
one, all of them being equally likely given only the information on the ratio.
As a consequence, the value of the frequency in the denominator $f_{t}^{(n)}$ is
restricted to fall in the range
$$
f_{t}^{(n)} \in \left(0, \frac{1}{\gamma_t^{(n)}} \right].
$${#eq-freq_given_gamma_range}
A priori, we do not have any reason to favor any value over any other, therefore
it is natural to write
$$
f_t^{(n)} \mid \gamma_t^{(n)} \sim 
\operatorname{Uniform}\left( 0, \frac{1}{\gamma_t^{(n)}} \right).
$${#eq-f_given_gamma_uniform}

#### Summary

Putting all the pieces we have developed in this section together results in an
inference for the population mean fitness values of the form
$$
\pi(
    \underline{\bar{s}}_T, \underline{\sigma}_T \mid \underline{\underline{F}}
) \propto
\prod_{t=1}^{T-1} \left\{
    \prod_{n=1}^N \left[
        \pi(f_t^{(n)} \mid \gamma_t^{(n)}) 
        \pi(\gamma_t^{(n)} \mid \bar{s}_t, \sigma_t)
    \right]
    \pi(\bar{s}_t) \pi(\sigma_t)
\right\},
$${#eq-meanfit_full_inference}
where we have
$$
f_t^{(n)} \mid \gamma_t^{(n)} \sim 
\operatorname{Uniform} \left(0, \frac{1}{\gamma_t^{(n)}} \right),
$${#eq-meanfit_eq1}
$$
\gamma_t^{(n)} \mid \bar{s}_t, \sigma_t \sim 
\log\mathcal{N}(\bar{s}_t, \sigma_t),
$${#eq-meanfit_eq2}
$$
\bar{s}_t \sim \mathcal{N}(0, \sigma_{\bar{s}_t}),
$${#eq-meanfit_eq3}
and
$$
\sigma_t \sim \operatorname{Half}-\mathcal{N}(0, \sigma_{\sigma_t}),
$${#eq-meanfit_eq4}
where $\sigma_{\bar{s}_t}$ and $\sigma_{\sigma_t}$ are free parameters we can
choose.