project:
  type: website
  output-dir: _output
  render:
    - paper.qmd

# Title
title: "Bayesian inference of relative fitness on high-throughput pooled competition assays"

# Authors
author:
  - name: Manuel Razo-Mejia
    orcid: 0000-0002-9510-0527
    email: mrazo@stanford.edu
    affiliations: 
      - ref: stanfordbio
    corresponding: true
  - name: Madhav Mani
    orcid: 0000-0002-5812-4167
    affiliations: 
      - ref: nwqbio
      - ref: nweng
  - name: Dmitri Petrov
    orcid: 0000-0002-3664-9130
    affiliations:
      - ref: stanfordbio
      - ref: stanfordcancer
      - ref: czb

# Author affiliations
affiliations:
  - id: stanfordbio
    number: 1
    name: Department of Biology, Stanford University
    city: Stanford
    state: CA
    country: USA
  - id: stanfordcancer
    number: 4
    name: Stanford Cancer Institute, Stanford University School of Medicine
    city: Stanford
    state: CA
    country: USA
  - id: nwqbio
    number: 2
    name: NSF-Simons Center for Quantitative Biology, Northwestern University
    city: Chicago
    state: IL
    country: USA
  - id: nweng
    number: 3
    name: Department of Engineering Sciences and Applied Mathematics, Northwestern University
    city: Chicago
    state: IL
    country: USA
  - id: czb
    number: 5
    name: Chan Zuckerberg Biohub
    city: San Francisco
    state: CA
    country: USA
    
# Keywords
keywords:
  - bayesian inference
  - variational inference
  - relative fitness
  - open-source
  - reproducible research

# # Abstract
# abstract: >
#   The tracking of lineage frequencies via DNA barcode sequencing enables the
#   quantification of microbial fitness. However, experimental noise coming from
#   biotic and abiotic sources complicates the computation of a reliable
#   inference. We present a Bayesian pipeline to infer relative microbial fitness
#   from high-throughput lineage tracking assays. Our model accounts for multiple
#   sources of noise and propagates uncertainties throughout all parameters in a
#   systematic way. Furthermore, using modern variational inference methods based
#   on automatic differentiation, we are able to scale the inference to a large
#   number of unique barcodes. We extend this core model to analyze
#   multi-environment assays, replicate experiments, and barcodes linked to
#   genotypes. On simulations, our method recovers known parameters within
#   posterior credible intervals. This work provides a generalizable Bayesian
#   framework to analyze lineage tracking experiments. The accompanying
#   open-source software library enables the adoption of principled statistical
#   methods in experimental evolution.
number-sections: false
bibliography: references.bib

website:
  navbar:
    left:
      - text: BarBay.jl
        href: https://mrazomej.github.io/BarBay.jl
    logo: logo.png
    right:
      - icon: github
        href: https://github.com/mrazomej/bayesian_fitness
      - icon: twitter-x
        href: https://twitter.com/mrazomej
  sidebar:
    alignment: left
    title: "Sidebar"
    logo: logo.png

format:
  html:
    theme: cosmo
    default-image-extension: png
    toc: true
    filters:
      - maintext-filter.lua
      - sitext-filter.lua
  pdf: 
    documentclass: scrartcl
    numbersections: true
    template: template.tex
    cite-method: biblatex
    default-image-extension: pdf
    include-in-header:
      - file: _preamble.tex
    biblio-style: phys
    keep-tex: true
    filters:
      - color-text-span.lua
      - maintext-filter.lua
      - sitext-filter.lua